### ISSUE TITLE
How to make this work?

### ISSUE THREAD

**Issue by fowi4hjte** [devclef/imiev-remote-heater#1]
Its great to see this, but how can this be used? Are you using CAN? What hardware? What is the imiev build date this have been tested with? Is this imiev with remote heater fob or a imiev without remote heater fob and thanks to the code listed here you can enable the heater by remote for the first time?

**Comment by devclef** [comment]
Oh, sorry this does not do what you think :( I'll update the readme/project to make it more clear, sorry for the false hope.

I never found anyone that managed to send any commands to an imiev (even unlock/lock, windows, etc) let alone the remote heater commands. There is some folks on the forums with various dumps, and info but to my knowledge noone has ever found and shared any sort of 'write' capabilities to imiev. 

I spent some time trying to figure it out myself, no experience with CAN before, and another repo here was an attempt to make a .dbc file atleast. 

Ultimately I installed a small diesel heater in the back of the imiev, which had a small remote. This code can trigger the heater by replicating the code from that remote.  At the time I called the repo imiev-remote-heater for that reason, but in hindsight can see this casuses confusion. Sorry! 

This code is just a simple arduino program to send a specific message to a chinese diesel heater mimicing it's remote. Has nothing to do with the imiev specifically other than the car in which I installed this into :)
